# Generated by Django 5.1.7 on 2025-03-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=300, verbose_name='Ad')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.gender', verbose_name='Cinsi'),
        ),
    ]
