# Generated by Django 5.1.7 on 2025-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
