# Generated by Django 5.1.7 on 2025-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_author_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='coupon',
        ),
        migrations.AddField(
            model_name='product',
            name='coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
