# Generated by Django 5.1.7 on 2025-04-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
            ],
            options={
                'verbose_name': 'SalesProduct',
                'verbose_name_plural': 'SalesProduct',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
    ]
