# Generated by Django 5.1.7 on 2025-04-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_newcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.author')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            bases=('product.author',),
        ),
        migrations.AlterModelOptions(
            name='salesproduct',
            options={'verbose_name': 'Endirimli Mehsullar', 'verbose_name_plural': 'Endirimli Mehsullar'},
        ),
    ]
