# Generated by Django 5.1.7 on 2025-04-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_authorprofile_alter_salesproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
